

Table Users {
  id integer [primary key]
  username varchar [not null]
  name varchar
  phone varchar
  email varchar [not null]
  ranking integer 
  psw varchar [note: 'hashed']
  MFA bool [note: 'true send random email pin']
  tournomant integer
  registed timestamp
  last_login timestamp [default: `now()`]
}

Table Games_1v1_goals {
  timestamp timestamp [default: `now()`]
  interupt bool
  player1_points integer
  player2_points integer
  id integer [primary key]
}

Table Games_1v1 {
  player1_id integer
  player2_id integer
  games_id integer [primary key]
}


Table Tournament_games {
  player1_id integer
  player1_tournamentname varchar
  player2_id integer
  player2_tournamentname varchar
  player3_id integer
  player3_tournamentname varchar
  player4_id integer
  player4_tournamentname varchar
  player5_id integer
  player5_tournamentname varchar
  player6_id integer
  player6_tournamentname varchar
  player7_id integer
  player7_tournamentname varchar
  player8_id integer
  player8_tournamentname varchar
  games_id integer [primary key]
}

Table Tournament_goals {
  timestamp timestamp [default: `now()`]
  interupt bool
  player1_id integer
  player1_points integer
  player2_id integer
  player2_points integer
  id integer [primary key]
}


Ref : Users.id < Games_1v1.player1_id
Ref : Users.id < Games_1v1.player2_id
Ref : Games_1v1_goals.id > Games_1v1.games_id


Ref : Users.id < Tournament_games.player1_id
Ref : Users.id < Tournament_games.player2_id
Ref : Users.id < Tournament_games.player3_id
Ref : Users.id < Tournament_games.player4_id
Ref : Users.id < Tournament_games.player5_id
Ref : Users.id < Tournament_games.player6_id
Ref : Users.id < Tournament_games.player7_id
Ref : Users.id < Tournament_games.player8_id
Ref : Tournament_goals.id > Tournament_games.games_id





