

Table Users {
  id integer [primary key]
  username varchar [not null]
  name varchar
  phone varchar
  email varchar [not null]
  ranking integer 
  psw varchar [note: 'hashed']
  MFA bool [note: 'true send random email pin']
  games_1v1 integer
  tournomant integer
  registed timestamp
  last_login timestamp [default: `now()`]
}

Table Games_1v1_goals {
  timestamp timestamp [default: `now()`]
  interupt bool
  player1_first_points integer
  player2_points integer
  id integer [primary key]
}

Table User_games {
  player1_username_id integer
  player2_username_id integer
  games_id integer
  id integer [primary key]
}

Table Games_1v1_singelgames {
  timestamp timestamp [default: `now()`]
  interupt bool
  first_username_id integer
  first_points integer
  second_username_id integer
  second_points integer
  id integer [primary key]
}

Table Tournament_goals {
  timestamp timestamp [default: `now()`]
  interupt bool
  tournmaent_1v7 bool [note: 'false-> set NULL to fifth till eight']
  tournament_name varchar
  
  first_username_id integer
  first_tounamentname varchar
  first_points integer

  second_username_id integer
  second_tounamentname varchar
  second_points integer
 

  third_username_id integer
  third_tounamentname varchar
  third_points integer

  fourth_username_id integer
  fourth_tounamentname varchar
  fourth_points integer


  fifth_username_id integer
  fifth_tounamentname varchar
  fifth_points integer


  sixth_username_id integer
  sixth_tounamentname varchar
  sixth_points integer


  seventh_username_id integer
  seventh_tounamentname varchar
  seventh_points integer

  eighth_username_id integer
  eighth_tounamentname varchar
  eighth_points integer
  id integer [primary key]
  single_games integer
}

Table Tournament_singelgames {
  timestamp timestamp [default: `now()`]
  interupt bool
  first_username_id integer
  first_points integer
  second_username_id integer
  second_points integer
  id integer [primary key]
}

Ref : Users.games_1v1 <> Games_1v1_goals.id
Ref : Users.id - Games_1v1_goals.first_username_id
Ref : Users.id - Games_1v1_goals.second_username_id

Ref : Users.tournomant <> Tournament_goals.id
Ref : Users.id - Tournament_goals.first_username_id
Ref : Users.id - Tournament_goals.second_username_id
Ref : Users.id - Tournament_goals.third_username_id
Ref : Users.id - Tournament_goals.fourth_username_id
Ref : Users.id - Tournament_goals.fifth_username_id
Ref : Users.id - Tournament_goals.sixth_username_id
Ref : Users.id - Tournament_goals.seventh_username_id
Ref : Users.id - Tournament_goals.eighth_username_id

Ref : Tournament_goals.single_games <> Tournament_singelgames.id


Ref : Games_1v1_goals.single_games <> Games_1v1_singelgames.id